### PR TITLE
add precision on how many time Swan servers await before considering a webhook as failed

### PR DESCRIPTION
**Pull request by anwar-piloc**

### CODE REVIEW

**Comment by clywyk** [comment]
@bloodyowl or @zoontek, could you please confirm that this updated webhook behavior is correct? Do our servers wait 30 seconds or 15 to retry (in Live)? Thanks!

**Comment by bloodyowl** [comment]
not our scope, you need to ask PXP

**Comment by anwar-piloc** [comment]
@clywyk if it can help, this is the answer from the support (Florian C. - Customer Support Specialist). This means my statement is incorrect, we should write:

- 5 sec timeout (sandbox)
- 15 sec timeout (prod)

Do you want me to make the change?

Capture d’écran 2024-11-12 à 14 52 29

**Comment by clywyk** [comment]
Hey @anwar-piloc , I confirmed with our team and the documentation is correct. Sometimes, calls timeout elsewhere (possibly on your side, but not on Swan's side), in which case we close the call. That's where you get the 5 seconds in Sandbox, 15 seconds in Live—that's how long we wait before closing the call when the timeout is elsewhere. Then, our webhook mechanism retries as described in the doc.

Closing this PR. Please don't hesitate to speak with your Technical Account Manager (TAM) with further questions. Technical questions like this should go through TAMs rather than Support.

Thanks again for your commitment to the doc! I look forward to more in the future if needed. 😊

**Pull request closed without merging**
